Template/Template/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Template import views  
from Template.views import Search 

search = Search()

urlpatterns = [
    path('', views.index, name="index"),
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path("success/", views.success, name="success"),
    path('search/', search.search, name='search'),
    
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    # path('accounts/', include('accounts.urls', namespace='accounts')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('myapp/', include('myapp.urls', namespace='myapp')),
    # path('search/', include('haystack.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Template/api/urls.py
from django.urls import path, include

from . import views 
from .views import *


from Template.arguments import *
from myapp.arguments import *
from users.arguments import *

app_name = 'api'

# general = General()


urlpatterns = [

    path(r"", views.getRoutes, name="getRoutes"), #mapping the homepage function
    # path(r"", General.as_view(), name="getRoutes"), #mapping the homepage function
    path(r"search/", views.search, name="api-search"), 
    path(r"all/", views.view_all, name="all"),
    path(r"add/", views.add, name="add"),
    path(r"view/<int:key>", views.view, name="view"),
    path(r"update/<int:key>", views.update, name="update"),
    path(r"delete/<int:key>", views.delete, name="delete"),
                 



  
]

Template/users/urls.py
from django.urls import path, include
from users import views  #importing our view file 
# from .views import Add_user_form
from django.urls import path
from users import views 
from users.views import * 

app_name = 'users'

user = User()
group = Group()
content = Content()
permission = Permission()
level = Level()
role = Role()
# user_group = UserGroup()
# user_role = UserRole()
# group_role = GroupRole()
search = Search()

urlpatterns = [
    path(r"", views.index, name="index"), #mapping the homepage function

    path("search/", group.search, name="search"),
    path("login/", group.search, name="login"),
    path("logout/", group.search, name="logout"),
    path("register/", group.search, name="register"),
    path("password-change/", group.search, name="password-change"),
                   
    path("view-all-users/", user.view_all, name="view-all-users"),
    path("add-user/", user.add, name="add-user"),
    path("view-user/<int:key>", user.view, name="view-user"),
    path("update-user/<int:key>", user.update, name="update-user"),
    path("delete-user/<int:key>", user.delete, name="delete-user"),


   
    path("view-all-groups/", group.view_all, name="view-all-groups"),
    path("add-group/", group.add, name="add-group"),
    path("view-group/<int:key>", group.view, name="view-group"),
    path("update-group/<int:key>", group.update, name="update-group"),
    path("delete-group/<int:key>", group.delete, name="delete-group"),

                 
    path("view-all-contents/", content.view_all, name="view-all-contents"),
    path("add-content/", content.add, name="add-content"),
    path("view-content/<int:key>", content.view, name="view-content"),
    path("update-content/<int:key>", content.update, name="update-content"),
    path("delete-content/<int:key>", content.delete, name="delete-content"),
                                     
    path("view-all-permissions/", permission.view_all, name="view-all-permissions"),
    path("add-permission/", permission.add, name="add-permission"),
    path("view-permission/<int:key>", permission.view, name="view-permission"),
    path("update-permission/<int:key>", permission.update, name="update-permission"),
    path("delete-permission/<int:key>", permission.delete, name="delete-permission"),
    
    path("view-all-roles/", role.view_all, name="view-all-roles"),
    path("add-role/", role.add, name="add-role"),
    path("view-role/<int:key>", role.view, name="view-role"),
    path("update-role/<int:key>", role.update, name="update-role"),
    path("delete-role/<int:key>", role.delete, name="delete-role"),
    
    path("view-all-levels/", level.view_all, name="view-all-levels"),
    path("add-level/", level.add, name="add-level"),
    path("view-level/<int:key>", level.view, name="view-level"),
    path("update-level/<int:key>", level.update, name="update-level"),
    path("delete-level/<int:key>", level.delete, name="delete-level"),
         
    # path("view-all-user-groups/", user_group.view_all, name="view-all-user-groups"),
    # path("add-user-group/", user_group.add, name="add-user-group"),
    # path("view-user-group/<int:key>", user_group.view, name="view-user-group"),
    # path("update-user-group/<int:key>", user_group.update, name="update-user-group"),
    # path("delete-user-group/<int:key>", user_group.delete, name="delete-user-group"),
                 
    # path("view-all-user-permission/", user_role.view_all, name="view-all-user-permission"),
    # path("add-user-permission/", user_role.add, name="add-user-permission"),
    # path("view-user-permission/<int:key>", user_role.view, name="view-user-permission"),
    # path("update-user-permission/<int:key>", user_role.update, name="update-user-permission"),
    # path("delete-user-permission/<int:key>", user_role.delete, name="delete-user-permission"),
   
    # # path("approve-user-permission/<str:key>", views.approve_group, name="approve-group"),
                  
    # path("view-all-group-permission/", group_role.view_all, name="view-all-group-permission"),
    # path("add-group-permission/", group_role.add, name="add-group-permission"),
    # path("view-group-permission/<int:key>", group_role.view, name="view-group-permission"),
    # path("update-group-permission/<int:key>", group_role.update, name="update-group-permission"),
    # path("delete-group-permission/<int:key>", group_role.delete, name="delete-group-permission"),

]

Template/Template/templates/assurance.html
{% extends 'base.html' %}

{% block content %}
 
    <h1 class="h3 mb-3 font-weight-normal">{{title}} {{action}} {{page_type}}</h1>

    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                <div class="card-panel green lighten-2">{{message}}</div>
            {% endif %}
        {% endfor%}
    {% endif %} 
    
    <p> <h3> Are you sure to {{action}} The {{instance_type}} {{instance}}</h3></p>
    <form action="" enctype="multipart/form-data" method="POST"> 
       
        {% csrf_token %}
        <br/>
        {% if instance_type != 'Analysis' %}
            {% with view_all_url=app|add:':'|add:view_all_url %}
                <a class="waves-effect waves light btn-large" href="{% url view_all_url %}" class="waves-effect waves light btn-large">Cancel</a>
            {% endwith %}
            <button class="waves-effect waves light btn-large" type="submit">{{action}} {{instance_type}}</button>
       {% else %}
            <a class="waves-effect waves light btn-large" href="{% url 'myapps:view-analysises' instance.instance1.id %}" class="waves-effect waves light btn-large">Cancel</a>
            <button class="waves-effect waves light btn-large" type="submit"  name ="submit" value="delete-analysis">{{action}} {{instance_type}}</button>
        {% endif %} 
        <!-- <button class="btn btn-lg btn-primary btn-block" type="submit" value="Add User">Add User</button> -->


        {% if instance_type != 'Analysis' %}
            {% with view_all_url=app|add:':'|add:view_all_url %}
                <a class="waves-effect waves light btn-large" href="{% url view_all_url %}" >View All {{title}}</a>  
            {% endwith %}
        {% endif %} 

    </form>
    
{% endblock content %}

Template/Template/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes"> <!--# no -->
    <!-- <link as="script" rel="preload" href="{% static 'js/html2canvas.js' %}"/> 
        <link as="script" rel="preload" href="{% static 'js/main.js' %}"/> 
        <link as="script" rel="preload" href="{% static 'js/materializedatetimepicker.js' %}"/> 
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}"> -->    

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />

    <title>Base html -   {{title}} {{page_type}}</title>
  
</head>
<body >
    <nav>    
        <div class="nav-wrapper">
            
          <a href="{% url 'index' %}" class="brand-logo">
              <img class="img-fluid mx-auto d-block" src="{% static 'img/INSA.jpg' %}" alt="logo image" width="100%" height="100%">
            </a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li>    
                <div class="center row">
                <div class="col s12 " >
                    <div class="row" id="topbarsearch">
                    <div class="input-field col s6 s12 red-text">
                        <i class="red-text material-icons prefix">search</i>
                        <input type="text" placeholder="search" id="autocomplete-input" class="autocomplete red-text" >
                        </div>
                    </div>
                    </div>
                </div>          
            </li>  
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
            
            {% if user.is_authenticated %}
                <li><a href="{% url 'users:logout' %}">Logout</a></li>
                <li><a href="{% url 'users:password-change' %}">Change password</a></li>
      
            {% else %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:register' %}">Register</a></li>
            {% endif %} 
    
    </ul>
        </div>
   </nav>

  <div class="container">
      {% block content %}
  
      {% endblock content %}
  </div>

  <div class="container">
        <p> <a class="waves-effect waves light btn-large" href="{{ request.META.HTTP_REFERER }}">Back</a></p>
  </div>


{% block javascript %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>   
    <script src=" {% static 'js/main.js'"></script>   
    <script src=" {% static 'js/materializedatetimepicker.js'"></script>
    <script>
       $(document).ready(function(){
                    M.AutoInit();
                    var DateTimeField = MaterialDateTimePicker.create($('input'))
        // Initialize materialize data picker
       $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
       $('.timepicker').timepicker();
        // $('.datetimepicker').datetimepicker();/
        $('select').formSelect();
        });
    </script>
  
    <script>
        $(".nav-wrapper").css("background-color", 'darkblue');
        $(".secondary-content>.material-icons").css("color", 'purple');
        $(".btn").css("background-color", 'purple');
        $(".page-footer").css("background-color", 'purple');
        $(".input-field").css("color", 'purple');
        $(".input-field>.material-icons").css("color", 'purple');
        $(".input-field>label").css("color", 'purple');
    </script>
   
{% endblock javascript %}

</body>


</html>

Template/Template/templates/base_image.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes"> <!--# no -->
    <!-- <link as="script" rel="preload" href="{% static 'js/html2canvas.js' %}"/>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}"> -->    

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />

    <title>Base html -   {{title}} {{page_type}}</title>
  
</head>
<body ><nav>
      
  
        <div class="nav-wrapper">
            
          <a href="{% url 'index' %}" class="brand-logo">
              <img class="img-fluid mx-auto d-block" src="{% static 'img/INSA.jpg' %}" alt="logo image" width="100%" height="100%">
            </a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li>    
                <div class="center row">
                <div class="col s12 " >
                    <div class="row" id="topbarsearch">
                    <div class="input-field col s6 s12 red-text">
                        <i class="red-text material-icons prefix">search</i>
                        <input type="text" placeholder="search" id="autocomplete-input" class="autocomplete red-text" >
                        </div>
                    </div>
                    </div>
                </div>          
            </li>  
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
            
            {% if user.is_authenticated %}
                <li><a href="{% url 'users:logout' %}">Logout</a></li>
                <li><a href="{% url 'users:password_change' %}">Change password</a></li>
      
            {% else %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:register' %}">Register</a></li>
            {% endif %} 
    
    </ul>
        </div>
      </nav>

  


  <div class="container">
      {% block content %}
  
      {% endblock content %}
  </div>

  <div class="container">
        <p> <a href="{{ request.META.HTTP_REFERER }}">Back</a></p>
  </div>


  <div id="capture" style="padding: 10px; background: #f5da55">
    <h4 style="color: #000; ">Hello world!</h4>
</div>

{% block javascript %}
    <script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>   
    <script src=" {% static 'js/main.js"></script>   
    <script src=" {% static 'js/materializedatetimepicker.js"></script>  
    <script>
        $(document).ready(function(){
                    M.AutoInit();
                    var DateTimeField = MaterialDateTimePicker.create($('input'))
        // Initialize materialize data picker
       // $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
       // $('.timepicker').timepicker();
        //$('select').formSelect();
        });
    </script>
  
   
{% endblock javascript %}

</body>

<script>
//     import React, { Fragment, useState } from "react";
//     import { DateTimePicker } from "@material-ui/pickers";
    
//     function BasicDateTimePicker() {
//       const [selectedDate, handleDateChange] = useState(new Date());
    
//       return (
//         <Fragment>
//           <DateTimePicker
//             label="DateTimePicker"
//             inputVariant="outlined"
//             value={selectedDate}
//             onChange={handleDateChange}
//         //   />
    
//         //   <DateTimePicker
//         //     autoOk
//         //     ampm={false}
//         //     disableFuture
//         //     value={selectedDate}
//         //     onChange={handleDateChange}
//         //     label="24h clock"
//         //   />
    
//         //   <DateTimePicker
//         //     value={selectedDate}
//         //     disablePast
//         //     onChange={handleDateChange}
//         //     label="With Today Button"
//         //     showTodayButton
//           />
//         </Fragment>
//       );
//     }
    
//     export default BasicDateTimePicker;
// </script>
<script>
     $(".nav-wrapper").css("background-color", 'darkblue');
     $(".secondary-content>.material-icons").css("color", 'purple');
     $(".btn").css("background-color", 'purple');
     $(".page-footer").css("background-color", 'purple');
     $(".input-field").css("color", 'purple');
     $(".input-field>.material-icons").css("color", 'purple');
     $(".input-field>label").css("color", 'purple');
</script>
    <script>

        html2canvas(document.querySelector("#capture")).then(canvas => {
            document.body.appendChild(canvas)
        });

        $(function() { 
    $("#btnSave").click(function() { 
        html2canvas($("#widget"), {
            onrendered: function(canvas) {
                theCanvas = canvas;


                canvas.toBlob(function(blob) {
                    saveAs(blob, "Dashboard.png"); 
                });
            }
        });
    });
});
    </script>


<span id="widget" class="widget" field="AGE" roundby="20" description="Patient age, in years">
    
    <table ng-model="table" class="ng-pristine ng-valid">
      
      <thead>
        <tr>
          <th class="cell value">Value</th>
          <th class="cell freq">Freq</th>
          <th class="cell value"></th>
        </tr>
      </thead>
      <tbody>

      <tr ng-show="getShowMean()" class="">
        <td class="stat">Mean</td>
        <td class="ng-binding">46.1</td>
      </tr>


      </tbody>
    </table>

<!-- ngRepeat: field in getChildren(field) -->
</span>
<br/>
<input type="button" id="btnSave" value="Save PNG"/>

<div id="img-out"></div>



<script>

html2canvas(document.querySelector("#widget")).then(canvas => {
    document.body.appendChild(canvas)
});


</script>




</html>
<span id="widget" class="widget">dfgdfg</span>
<input type="button" id="btnSave" value="Save PNG"/>
<div id="img-out"></div>

<script>

$(function() { 
    $("#btnSave").click(function() { 
        html2canvas($("#widget"), {
            onrendered: function(canvas) {                
                document.body.appendChild(canvas);
                canvas.toBlob(function(blob) {saveAs(blob, "new.png")});
            }
        });
    });
}); 
</script>

Template/Template/templates/form.html
{% extends 'base.html' %}
{% load materializecss %}

{% block content %}
 
    <h1 class="h3 mb-3 font-weight-normal">{{title}} {{action}} {{page_type}}</h1>
    {% if title == 'Analysis' %}
            <h2>For  {{instance}}</h2>

    {% endif %}
    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                <div class="card-panel green lighten-2">{{message}}</div>
            {% endif %}
        {% endfor%}
    {% endif %}

    <form action="" enctype="multipart/form-data" method="POST"> 
       
        {% csrf_token %}
        {{ form|materializecss }}
        <br/>
        {% if action == 'Update' %}    
            <button class="waves-effect waves light btn-large" type="submit" value="save" name="submit">{{action}} {{instance_type}}</button>
        {% else %}
            <button class="waves-effect waves light btn-large" type="submit" value="save" name="submit">Save {{instance_type}}</button>
            <button class="waves-effect waves light btn-large" type="submit" value="add" name="submit">Save and {{action}} another {{instance_type}}</button>
            <!-- <button class="btn btn-lg btn-primary btn-block" type="submit" value="Add User">Add User</button> -->
        {% endif %}
        {% if instance_type != 'Initial Analysis' %}
            {% with view_all_url=app|add:':'|add:view_all_url %}
                <a class="waves-effect waves light btn-large" href="{% url view_all_url %}" >View All {{title}}</a>  
            {% endwith %}
        {% endif %} 
    </form>


{% endblock content %}

Template/Template/templates/index.html
{% extends 'base.html' %}

{% block title %}
    {{title}} {{page_type}}
{% endblock title %}

{% block content %}

{% csrf_token %}

  <h1 class="h3 mb-3 font-weight-normal"> {{title}} {{page_type}}</h1>


<div class="d-flex flex-column">
    <a class="m-auto" href="{% url 'users:register' %}">Register</a>
    <a class="m-auto" href="{% url 'users:login' %}">Login</a>
</div>

<a class="m-auto" href="{% url 'users:index' %}">Users</a>
{% endblock content %}

Template/Template/templates/must_authenticate.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">You must authenticate to view this page. </p>
		<p class="m-auto">
			<a href="{% url 'users:register' %}">Create an account</a> or 
			<a href="{% url 'users:login' %}">login</a>.
		</p>
	</div>
</div>

{% endblock content %}

Template/Template/templates/pdf.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Report PDF</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">

        <style type="text/css">
            tr{
                border : 1px solid #000;
                padding: 10px !important;
                margin: 10px;
            }
            @page {
                size: A4;
                margin: 1cm;
                /* @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                } */
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h2>Report - {{today | date:"d/m/Y"}}</h2>

                </div>
                <table>
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>header 1</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td class="text-center"> data</td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
        <div id="footerContent">
            {%block page_foot%}
                Page <pdf:pagenumber>
            {%endblock%}
        </div>
    </body>
</html>

Template/Template/templates/report.html
{% extends 'base.html' %}
{% load extras %}

{% block title %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>My Title</title>
        <style type="text/css">
            @page {
                /* size: {{ pagesize }}; */
                size: 'A4';
                margin: 1cm;
                /* @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                } */
            }
        </style>
    </head>

    {{title}} {{page_type}}
{% endblock title %}
{% block css %}


{% endblock css %}
{% block content %}
 
    <h1 class="h3 mb-3 font-weight-normal">{{instance_type}} {{action}} {{page_type}}</h1>

    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                <div class="card-panel green lighten-2">{{message}}</div>
            {% endif %}
        {% endfor%}
    {% endif %}
 
    {% csrf_token %}


{% if instances %}
 <table>
    <thead>
        <tr>
            <th>No</th>
            {% with fields=instances|get_field_names_from_instances %}

                {% for field_name in fields %}
                    {% if field_name != 'description' %}
                        
                        <th> {{ field_name | field_name_to_phrase }}   </th>

                    {% endif %} 
    
        
                {% endfor %} 
            {% endwith %} 
        </tr>
    </thead>

    <tbody> 
        {% for instance in instances %}  
        <div>              
            <tr>
                <td>{{ forloop.counter}}</td>
                {% for field_name, header_value in instance.items %}
                   <td>{{ header_value}}</td>
                {% endfor%}
            </tr> 
        </div> 
        {% endfor%}         
    </tbody>  
    
    

{% if instance %}    
<table>
    <thead>
        <tr>
            <td>Field Name  </td> 
            <td>Value </td>
        </tr>
    </thead>

    <tbody>
        
            <div>     
                {% for field_name, value in instance|get_all_field_value_pairs %}
                    {% if field_name != 'attachment_data' %}
                        {% if value %}
                        <tr>
                            <td> {{ field_name | field_name_to_phrase }}   </td>
                            <td> {{value}} </td>
                        </tr> 
                        {% endif %} 
                    {% endif %} 
                {% empty %}
                    <h1>Not Available</h1>
                {% endfor%}
                
            </div>
    
    </tbody>    
</table>  

  



{% endif %} 


</table>

    {% for instance in instances %} 
        <h1>{{ forloop.counter}}</h1>
        {% if instance.detail_info_set %}
            <h2><b>{{instance.code}}</b></h2>
            
            {% for detail in instance.detail_info_set.all %}
                <h3><b>Source:</b> {{detail.attachment_source.name}}</h3>   
                
                <img src="{{detail.attachment_data|get_binary}}" alt="Attachment here">
                <!-- <img src="{{detail.attachment.path}}" alt="Attachment here"> -->
            {% endfor %}
        {% endif %}
    {% endfor %} 

{% endif %}
    
        <div>
            {% for item in mylist %}
                RENDER MY CONTENT
            {% endfor %}
        </div>
        <div id="footerContent">
            {%block page_foot%}
                Page <pdf:pagenumber>
            {%endblock%}
        </div>
{% endblock content %}

Template/Template/templates/success.html
{% extends 'base.html' %}

{% block title %}
    {{title}} {{page_type}}
{% endblock title %}

{% block content %}

    <h1 class="h3 mb-3 font-weight-normal">{{title}} {{action}} {{page_type}}</h1>
  
    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                <div class="card-panel green lighten-2">{{message}}</div>
            {% endif %}
        {% endfor%}
    {% endif %}
    
    {% csrf_token %}  

    <div class="container">
        <a class="waves-effect waves light btn-large" href="{{ request.META.HTTP_REFERER }}">Back</a>
    </div>

{% endblock content %}
 <!-- <h1 class="h3 mb-3 font-weight-normal">{{ user.username|default:'Guest' }} has {{title}} successfully!</h1>
    <h1 class="h3 mb-3 font-weight-normal">{{ success_message|default:'Guest' }} has {{title}} successfully!</h1>
    <h1 class="h3 mb-3 font-weight-normal">{{ page_message|default:'Action Successful' }}!</h1>
    -->